name: Copybara PR

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  copybara:
    #if: contains(github.event.pull_request.labels.*.name, 'enhancement')
    permissions:
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup git
        run: |
          git config --global user.email "ci@connectorio.com"
          git config --global user.name "ConnectorIO Bot"
          git config --global url."https://${BUILD_USER}:${BUILD_TOKEN}@github.com/".insteadOf "ssh://git@github.com:"
          git config --global url."https://${BUILD_USER}:${BUILD_TOKEN}@github.com/".insteadOf "git://git@github.com:"
        env:
          BUILD_USER: x-access-token
          BUILD_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Cache copybara jar
        uses: actions/cache@v3
        with:
          path: bazel-bin/java/com/google/copybara/copybara_deploy.jar
          key: copybara
      - name: Call copybara
        # removed section
        # git config -l --global
        # echo $PATH
        # command -v git
        # export GIT_CURL_VERBOSE=1
        # export GIT_SSH_COMMAND=""
        # and copybara option --git-destination-url="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/code-house/maven-git-release-test.git" \
        run: |
          export GIT_SSH_COMMAND=""
          java -jar bazel-bin/java/com/google/copybara/copybara_deploy.jar \
          migrate .github/copy.bara.sky 3.1.x \
          ${{ github.event.pull_request.number }} \
          --git-destination-url="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/code-house/maven-git-release-test.git" \
          --last-rev ${{ github.event.pull_request.base.sha }}
