name: Copybara PR

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  copybara:
    #if: contains(github.event.pull_request.labels.*.name, 'enhancement')
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Cache copybara jar
        uses: actions/cache@v3
        with:
          path: bazel-bin/java/com/google/copybara/copybara_deploy.jar
          key: copybara
      - name: Call copybara
        run: |
          git config user.email "ci@connectorio.com"
          git config user.name "ConnectorIO Bot"
          git config --global url."https://${BUILD_USER}:${BUILD_TOKEN}@github.com/".insteadOf "ssh://git@github.com"
          git config --global url."https://${BUILD_USER}:${BUILD_TOKEN}@github.com/".insteadOf "git@github.com:"

          java -jar bazel-bin/java/com/google/copybara/copybara_deploy.jar \
          migrate .github/copy.bara.sky 3.1.x \
          ${{ github.event.pull_request.number }} \
          --verbose \
          --dry-run
        env:
          BUILD_USER: x-access-token
          BUILD_TOKEN: ${{ secrets.GITHUB_TOKEN }}